# Generated by Django 4.0.3 on 2022-06-01 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='like',
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_course', to=settings.AUTH_USER_MODEL, verbose_name='Оценка курса'),
        ),
    ]
