# Generated by Django 4.0.3 on 2022-06-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug_course',
        ),
    ]
