# Generated by Django 4.0.3 on 2022-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_slug_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course', verbose_name='Записанные курсы'),
        ),
    ]
